import json

# json_report.py
# Generates JSON risk reports
def generate_json_report(data, output_file):
    """
    Generates a comprehensive JSON risk report.

    Args:
        data (dict): The risk data to include in the report.
        output_file (str): Path to the output JSON file.

    Returns:
        bool: True if report generation succeeded, False otherwise.
    """
    try:
        # Add metadata as a lead to the report
        report = {
            "report_metadata": {
                "generated_by": "Risksense AI",
                "format": "JSON",
                "version": "1.0",
                "description": "Comprehensive risk report generated by Risksense AI"
            },
            "risk_data": data
        }
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=4, ensure_ascii=False)
        return True
    except (OSError, TypeError, ValueError) as e:
        print(f"Failed to generate JSON report: {e}")
        return False